name: Collect data descriptions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 5 * * *"


jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Collect and check some descriptions
      run: |
        python -m edits check iiasa-transport
        python -m edits check jmip
        python -m edits check miso2

    - name: Test the "demo" command
      run: |
        python -m edits demo
